# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_BCEndo_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_BCEndo_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_BCEndo_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_BCEndo_rcpparma_bothproducts`, x)
}

DF2mat <- function(x) {
    .Call(`_BCEndo_DF2mat`, x)
}

draw_regcoef_cpp <- function(y, X, sigma2, B0) {
    .Call(`_BCEndo_draw_regcoef_cpp`, y, X, sigma2, B0)
}

draw_regcoef_overparam_cpp <- function(y, X, sigma2, b0, B0) {
    .Call(`_BCEndo_draw_regcoef_overparam_cpp`, y, X, sigma2, b0, B0)
}

ffbs_cpp <- function(m0, C0, Y, F, G, V, W, N, TT) {
    .Call(`_BCEndo_ffbs_cpp`, m0, C0, Y, F, G, V, W, N, TT)
}

horseshoe_cpp <- function(y, X, Sigma2, tau, lambda) {
    .Call(`_BCEndo_horseshoe_cpp`, y, X, Sigma2, tau, lambda)
}

draw_beta_p0_l_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_beta_p0_l_cpp`, datP, paramp)
}

draw_individual_intercept_p0_i_l_overparam_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_individual_intercept_p0_i_l_overparam_cpp`, datP, paramp)
}

draw_alpha_p0_i_l_overparam_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_alpha_p0_i_l_overparam_cpp`, datP, paramp)
}

draw_alpha_p0_i_l_overparam_with_intercept_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_alpha_p0_i_l_overparam_with_intercept_cpp`, datP, paramp)
}

draw_gamma_p0_i_l_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_gamma_p0_i_l_cpp`, datP, paramp)
}

draw_gamma_p0_i_l_hs_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_gamma_p0_i_l_hs_cpp`, datP, paramp)
}

draw_xi_f_p0_t_l_cpp <- function(dataP, paramp0) {
    .Call(`_BCEndo_draw_xi_f_p0_t_l_cpp`, dataP, paramp0)
}

draw_xi_p0_t_l_with_intercept_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_xi_p0_t_l_with_intercept_cpp`, datP, paramp)
}

draw_xi_p0_t_l_intercept_only_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_xi_p0_t_l_intercept_only_cpp`, datP, paramp)
}

draw_xi_p0_t_l_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_xi_p0_t_l_cpp`, datP, paramp)
}

draw_f_p0_t_l_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_f_p0_t_l_cpp`, datP, paramp)
}

draw_phi_xi_p0_j_l_cpp <- function(dataP, paramp0) {
    .Call(`_BCEndo_draw_phi_xi_p0_j_l_cpp`, dataP, paramp0)
}

draw_phi_f_p0_j_l_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_phi_f_p0_j_l_cpp`, datP, paramp)
}

draw_sigma2_e_p0_j_l_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_sigma2_e_p0_j_l_cpp`, datP, paramp)
}

draw_sigma2_eps_p0_l_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_sigma2_eps_p0_l_cpp`, datP, paramp)
}

draw_pi_p0_j_l_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_pi_p0_j_l_cpp`, datP, paramp)
}

draw_theta_p0_l_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_theta_p0_l_cpp`, datP, paramp)
}

draw_tau2_p0_l_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_tau2_p0_l_cpp`, datP, paramp)
}

draw_s_p0_l_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_s_p0_l_cpp`, datP, paramp)
}

draw_p0_mis_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_p0_mis_cpp`, datP, paramp)
}

draw_p0_delta_cpp <- function(datP, paramp) {
    .Call(`_BCEndo_draw_p0_delta_cpp`, datP, paramp)
}

draw_phi_delta_p_cpp <- function(dataP, paramp0, addTimeTreandforDelta) {
    .Call(`_BCEndo_draw_phi_delta_p_cpp`, dataP, paramp0, addTimeTreandforDelta)
}

draw_sigma2_eta_p_cpp <- function(dataP, paramp0, addTimeTreandforDelta) {
    .Call(`_BCEndo_draw_sigma2_eta_p_cpp`, dataP, paramp0, addTimeTreandforDelta)
}

draw_beta_y0_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_beta_y0_cpp`, dataY, paramy0)
}

draw_individual_intercept_y0_overparam_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_individual_intercept_y0_overparam_cpp`, dataY, paramy0)
}

draw_alpha_y0_i_overparam_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_alpha_y0_i_overparam_cpp`, dataY, paramy0)
}

draw_alpha_y0_i_overparam_with_intercept_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_alpha_y0_i_overparam_with_intercept_cpp`, dataY, paramy0)
}

draw_gamma_y0_i_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_gamma_y0_i_cpp`, dataY, paramy0)
}

draw_gamma_y0_i_hs_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_gamma_y0_i_hs_cpp`, dataY, paramy0)
}

draw_xi_f_y0_t_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_xi_f_y0_t_cpp`, dataY, paramy0)
}

draw_xi_y0_t_with_intercept_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_xi_y0_t_with_intercept_cpp`, dataY, paramy0)
}

draw_xi_y0_t_intercept_only_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_xi_y0_t_intercept_only_cpp`, dataY, paramy0)
}

draw_xi_y0_t_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_xi_y0_t_cpp`, dataY, paramy0)
}

draw_f_y0_t_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_f_y0_t_cpp`, dataY, paramy0)
}

draw_phi_xi_y0_j_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_phi_xi_y0_j_cpp`, dataY, paramy0)
}

draw_phi_f_y0_j_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_phi_f_y0_j_cpp`, dataY, paramy0)
}

draw_sigma2_e_y0_j_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_sigma2_e_y0_j_cpp`, dataY, paramy0)
}

draw_sigma2_eps_y0_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_sigma2_eps_y0_cpp`, dataY, paramy0)
}

draw_pi_y0_j_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_pi_y0_j_cpp`, dataY, paramy0)
}

draw_theta_y0_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_theta_y0_cpp`, dataY, paramy0)
}

draw_tau2_y0_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_tau2_y0_cpp`, dataY, paramy0)
}

draw_s_y0_cpp <- function(dataY, paramy0) {
    .Call(`_BCEndo_draw_s_y0_cpp`, dataY, paramy0)
}

draw_y0_mis_cpp <- function(dataY, paramp0, paramy0) {
    .Call(`_BCEndo_draw_y0_mis_cpp`, dataY, paramp0, paramy0)
}

draw_y0_delta_cpp <- function(dataY, paramp0, paramy0) {
    .Call(`_BCEndo_draw_y0_delta_cpp`, dataY, paramp0, paramy0)
}

draw_phi_delta_y_cpp <- function(dataY, paramy0, addTimeTreandforDelta) {
    .Call(`_BCEndo_draw_phi_delta_y_cpp`, dataY, paramy0, addTimeTreandforDelta)
}

draw_sigma2_eta_y_cpp <- function(dataY, paramy0, addTimeTreandforDelta) {
    .Call(`_BCEndo_draw_sigma2_eta_y_cpp`, dataY, paramy0, addTimeTreandforDelta)
}

